# PointStat METplus Configuration

[config]

# List of applications (tools) to run.
PROCESS_LIST = REGRIDDATAPLANE

# time looping - options are INIT, VALID, RETRO, and REALTIME
# If set to INIT or RETRO:
#   INIT_TIME_FMT, INIT_BEG, INIT_END, and INIT_INCREMENT must also be set
# If set to VALID or REALTIME:
#   VALID_TIME_FMT, VALID_BEG, VALID_END, and VALID_INCREMENT must also be set
LOOP_BY = INIT

# Format of INIT_BEG and INIT_END using % items
# %Y = 4 digit year, %m = 2 digit month, %d = 2 digit day, etc.
# see www.strftime.org for more information
# %Y%m%d%H expands to YYYYMMDDHH
INIT_TIME_FMT = %Y%m%d%H

# Start time for METplus run - must match INIT_TIME_FMT
INIT_BEG = {{cdate}}

# End time for METplus run - must match INIT_TIME_FMT
INIT_END = {{cdate}}

# Increment between METplus runs (in seconds if no units are specified).
# Must be >= 60 seconds.
INIT_INCREMENT = 3600

# List of forecast leads to process for each run time (init or valid)
# In hours if units are not specified
# If unset, defaults to 0 (don't loop through forecast leads)
LEAD_SEQ = {{vx_leadhr_list}}

#
# Verbosity of MET logging output.  0 to 5; 0 is quiet, 5 is loud.
#
LOG_REGRID_DATA_PLANE_VERBOSITY = {{metplus_verbosity_level}}
#
# Specify the name of the METplus log file.
#
LOG_METPLUS = {LOG_DIR}/{{metplus_log_fn}}
#
# Specify the location and name of the final METplus conf file.
#
METPLUS_CONF = {OBS_REGRID_DATA_PLANE_OUTPUT_DIR}/metplus_final.{{metplus_config_fn}}
#
# Name to identify observation data in output.
#
OBTYPE = {{obtype}}
#
# Directory containing (observation) input to RegridDataPlane.
#
OBS_REGRID_DATA_PLANE_INPUT_DIR = {{obs_input_dir}}
#
# Directory in which to write output from RegridDataPlane.
#
# OUTPUT_BASE apparently has to be set to something; it cannot be left
# to its default value.  But it is not explicitly used elsewhere in this
# configuration file.
#
OUTPUT_BASE = {{output_dir}}
OBS_REGRID_DATA_PLANE_OUTPUT_DIR = {{output_dir}}
OBS_REGRID_DATA_PLANE_RUN = True

# End of [dir] section and start of [filename_templates] section.
[filename_templates]


###
# RegridDataPlane Settings
# https://metplus.readthedocs.io/en/latest/Users_Guide/wrappers.html#regriddataplane
###

OBS_REGRID_DATA_PLANE_INPUT_TEMPLATE = {{obs_input_fn_template}}
OBS_REGRID_DATA_PLANE_OUTPUT_TEMPLATE = {{output_fn_template}}
REGRID_DATA_PLANE_VERIF_GRID = {{fcst_fn_template}}
REGRID_DATA_PLANE_METHOD = {{regrid_method}}

REGRID_DATA_PLANE_WIDTH = 2

REGRID_DATA_PLANE_GAUSSIAN_DX = {{gaussian_dx}}

REGRID_DATA_PLANE_GAUSSIAN_RADIUS = {{gaussian_radius}}

###
# Field Info
# https://metplus.readthedocs.io/en/latest/Users_Guide/systemconfiguration.html#field-info
###

OBS_REGRID_DATA_PLANE_VAR1_INPUT_FIELD_NAME = AOD
OBS_REGRID_DATA_PLANE_VAR1_INPUT_LEVEL = (*,*)
OBS_REGRID_DATA_PLANE_VAR1_OUTPUT_FIELD_NAME = AOD

REGRID_DATA_PLANE_ONCE_PER_FIELD = True



